version: "3.7"
services:
  postgres:
    container_name: adjustable_invoice_db
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=adjustable_invoice
    ports:
      - 5430:5432
  adjustable_invoice:
    container_name: adjustable_invoice
    restart: always
    build:
      context: ..
      dockerfile: dev_scripts/Dockerfile
    environment:
      - FLASK_APP=adjustable_invoice
      - FLASK_ENV=development
      - FLASK_RUN_PORT=9999
    ports:
      - 9999:9999
    volumes:
      - ..:/adjustable_invoice
    depends_on:
      - postgres
    entrypoint:
      - /adjustable_invoice/dev_scripts/run_server.sh
