"""empty message

Revision ID: d2f067d60cf6
Revises: 1ef5923021d3
Create Date: 2019-07-07 20:33:16.918315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f067d60cf6'
down_revision = '1ef5923021d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_item_comment', sa.Column('line_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'line_item_comment', 'line_item', ['line_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'line_item_comment', type_='foreignkey')
    op.drop_column('line_item_comment', 'line_item_id')
    # ### end Alembic commands ###
